# Build Script: Compiles registry, FHIR JSONs, Notes, and Originals into viewer/data.js

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BaseDir = Resolve-Path "$ScriptDir\.."
$RegistryFile = "$BaseDir\registry.json"
$OutputFile = "$ScriptDir\data.js"

Write-Host "Compiling questionnaire data bundle..." -ForegroundColor Cyan

if (-not (Test-Path $RegistryFile)) {
    Write-Error "registry.json not found at $RegistryFile"
    exit 1
}

$registry = Get-Content -LiteralPath $RegistryFile -Raw | ConvertFrom-Json

function LoadItemContent($item) {
    # 1. Load FHIR JSON
    if ($item.sourceFhir) {
        $fhirPath = "$BaseDir\$($item.sourceFhir)"
        if (Test-Path -LiteralPath $fhirPath) {
            $rawJson = Get-Content -LiteralPath $fhirPath -Raw
            $item | Add-Member -MemberType NoteProperty -Name "fhirJson" -Value ($rawJson | ConvertFrom-Json) -Force
        }
    }

    # 2. Load Notes Markdown
    if ($item.sourceNotes) {
        $notesPath = "$BaseDir\$($item.sourceNotes)"
        if (Test-Path -LiteralPath $notesPath) {
            $notesContent = Get-Content -LiteralPath $notesPath -Raw
            $item | Add-Member -MemberType NoteProperty -Name "notesContent" -Value $notesContent -Force
        }
    }

    # 3. Load Original Markdown
    if ($item.sourceOriginal) {
        $origPath = "$BaseDir\$($item.sourceOriginal)"
        if (Test-Path -LiteralPath $origPath) {
            $origContent = Get-Content -LiteralPath $origPath -Raw
            $item | Add-Member -MemberType NoteProperty -Name "originalContent" -Value $origContent -Force
        }
    }
}

foreach ($block in $registry.buildingBlocks) {
    LoadItemContent $block
}

foreach ($case in $registry.caseDescriptions) {
    LoadItemContent $case
}

$bundleJson = $registry | ConvertTo-Json -Depth 20
$bundleJs = "// Auto-generated by build-bundle.ps1`nwindow.QUESTIONNAIRE_REGISTRY_DATA = $bundleJson;`n"

Set-Content -LiteralPath $OutputFile -Value $bundleJs -Encoding UTF8

Write-Host "Bundle generated successfully at $OutputFile" -ForegroundColor Green
